### ISSUE TITLE
proposed features

### ISSUE THREAD

**Issue by dashmiller** [kenneththomas/ari4#1]
respond to + with +
"4 inches is all you need"
go to bed script based on midnight in diff time zoned
admin commands to clear counters

**Comment by kennethwoo** [comment]
if message.content.startswith('+'):
        willitsay = random.randint(1,3)
        if willitsay == 1:
            await client.send_typing(message.channel)
            time.sleep(.5)
            msg = '+'
            await client.send_message(message.channel, msg)

**Comment by kennethwoo** [comment]
clearing drama is fairly simple but need a way to make sure only admins can use the command

**Comment by dashmiller** [comment]
next time i will not propose 4 features in one issue because this shit will never be closed rofl
